name: no_imagination
dependencies:
- python=3.6.1
- numpy==1.13.0
- scipy==0.19.0
- scikit-image==0.13.0
- pandas
- matplotlib
- pip:
    - future==0.16.0
    - Flask==0.11.1
    - gevent==1.2.1
    - Flask-Cors==2.1.2
    - Flask-Security==1.7.5
    - Flask-SQLAlchemy==2.1
    - git+https://github.com/ansrivas/pylogging.git
    - gunicorn==19.7.1
    - tensorflow-gpu==1.1.0
    - circus==0.14.0
    - tqdm
    - keras
