name: no_imagination
channels:
    - defaults
dependencies:
- python=3.6.1
- numpy==1.13.0
- scipy==0.19.0
- scikit-image==0.13.0
- pandas
- matplotlib
- pip:
    - tensorflow-gpu==1.1.0
    - git+https://github.com/ansrivas/pylogging.git
    - circus==0.14.0
